// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3BiXw18rhiFkPtRsLP7mfHlksav-Zi_I',
    appId: '1:1036397495089:web:4aaa60d90d2dc13166e610',
    messagingSenderId: '1036397495089',
    projectId: 'canteen-application-demo',
    authDomain: 'canteen-application-demo.firebaseapp.com',
    storageBucket: 'canteen-application-demo.firebasestorage.app',
    measurementId: 'G-4CSDX01ND6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRfaZo5520n1N8zdhv665k7-yTQC-9N-g',
    appId: '1:1036397495089:android:b5bca116b7e4fe1166e610',
    messagingSenderId: '1036397495089',
    projectId: 'canteen-application-demo',
    storageBucket: 'canteen-application-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt6IQcrZYQ9sDI5pXZ1bSTVl-DLEaTwLk',
    appId: '1:1036397495089:ios:ff0f947772f947fb66e610',
    messagingSenderId: '1036397495089',
    projectId: 'canteen-application-demo',
    storageBucket: 'canteen-application-demo.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt6IQcrZYQ9sDI5pXZ1bSTVl-DLEaTwLk',
    appId: '1:1036397495089:ios:ff0f947772f947fb66e610',
    messagingSenderId: '1036397495089',
    projectId: 'canteen-application-demo',
    storageBucket: 'canteen-application-demo.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3BiXw18rhiFkPtRsLP7mfHlksav-Zi_I',
    appId: '1:1036397495089:web:2ba7359b006aefd266e610',
    messagingSenderId: '1036397495089',
    projectId: 'canteen-application-demo',
    authDomain: 'canteen-application-demo.firebaseapp.com',
    storageBucket: 'canteen-application-demo.firebasestorage.app',
    measurementId: 'G-TD6SL5ZHTR',
  );
}
